spring:
#  datasource:
#    url: jdbc:h2:mem:onclick;MODE=MYSQL
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oneClick?serverTimezone=Asia/Seoul
    username: bokyung
    password: a*01030337915

  jpa:
    defer-datasource-initialization: true
#    database-platform: H2
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    secret: gang
